apiVersion: management.loft.sh/v1
kind: Project
metadata:
  name: tenants-dev
spec:
  displayName: tenants-dev
  owner:
    user: admin
    team: loft-admins
  allowedClusters:
    - name: '*'
  allowedTemplates:
    - kind: VirtualClusterTemplate
      group: storage.loft.sh
      name: '*'
  members:
    - clusterRole: loft-management-project-admin
      group: storage.loft.sh
      kind: Team
      name: loft-admins
  access:
    - name: loft-admins-access
      verbs:
        - get
        - update
        - patch
        - delete
      subresources:
        - '*'
      users:
        - admin
      teams:
        - loft-admins
  quotas: {}
  requirePreset: {}
  requireTemplate:
    disabled: true
